"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: rosgraph_msgs.msg.dds_
  IDL file: Clock_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional
from dataclasses import dataclass

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import rosgraph_msgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class Clock_(idl.IdlStruct, typename="rosgraph_msgs.msg.dds_.Clock_"):
    clock: 'unitree_sdk2py.idl.builtin_interfaces.msg.dds_.Time_'
