"""
  Generated by Eclipse Cyclone DDS idlc Python Backend
  Cyclone DDS IDL version: v0.11.0
  Module: tf2_msgs.msg.dds_
  IDL file: TFMessage_.idl

"""

from enum import auto
from typing import TYPE_CHECKING, Optional, List
from dataclasses import dataclass, field

import cyclonedds.idl as idl
import cyclonedds.idl.annotations as annotate
import cyclonedds.idl.types as types

# root module import for resolving types
# import tf2_msgs


@dataclass
@annotate.final
@annotate.autoid("sequential")
class TFMessage_(idl.IdlStruct, typename="tf2_msgs.msg.dds_.TFMessage_"):
    transforms: types.sequence['unitree_sdk2py.idl.geometry_msgs.msg.dds_.TransformStamped_']

